spring.application.name=taco-cloud

spring.datasource.generate-unique-name=false
spring.datasource.name=tacocloud
spring.datasource.username=sa
spring.datasource.password=sa

spring.thymeleaf.cache=false

# Configuración JPA/Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true